import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ProfileChildTabs from "@/components/tabs/ProfileChildTabs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Member Profile Info",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { mId: number };
}) {
  return (
    <div>
      <ProfileChildTabs id={params.mId} />
      <hr className="bg-mainColor m-auto"></hr>
      {children}
    </div>
  );
}
