import type { Metadata } from "next";
import { Inter } from "next/font/google";
import VisitsChildTabs from "@/components/tabs/VisitsChildTabs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Member Visits",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { mId: number };
}) {
  return (
    <div>
      <VisitsChildTabs id={params.mId}/>
      <hr className="bg-mainColor m-auto"></hr>
      <div className="flex justify-center items-center">{children}</div>
    </div>
  );
}
