import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar/Nav.jsx";
import Footer from "../components/footer/Footer.jsx";
import Sidebar from "@/components/sidebar/Sidebar";
import NextAuthProvider from "@/context/AppProviders";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Lnkr",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <NextAuthProvider>
          <div className="w-full min-h-screen bg-bgColor ">
            <Navbar />
            <Sidebar />
            <div className="container min-w-full h-screen">{children}</div>
            <Footer />
          </div>
        </NextAuthProvider>
      </body>
    </html>
  );
}
